language: node_js
branches:
  except:
  - gh-pages
sudo: true
dist: trusty
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
env:
  global:
  - secure: "ABOZFV98X1M5YfRql9xXV192NrNlRSrqCZp+gEEUg0Q3EXx1QlBTJFP2ErXLPjCX188+hyF2Vz5OCJkfWe3gBkjlcfRGBkaza0ULNWGcdOXLdhhJ3R+fnxvqnrvCzABaLKEwb4AYYyOnR475Crsb6YQf5+lEgM1XUHjvfJ4+v6uyn0gCeUGMDQ1zU5V4vMY7VsMrXg/xf3/QOb0jTj39CuWGBzoS5Cxl04mIJh0gw6ei6m0btJZQBly40SPYXsCw/6xuqBz137bFBuDUtXBeYc1r7HCaUfkJhSbbI+FvL2rIzUAwdGvYQO4fWxc55Az0GV7EFgbl7f0D2a3GyytZxseQ3wIyuXWPcNKx2CCaPWcA8tj6/Api5gHgXhLW8Qo9q0KvhqvwvRLm/s8aO9K5HwxjcaY5I1pGzdxenxEjzjC+oUrLmjbl0L4H+h3oI0JZjiktA5GkYHMLsk6kH3iWtL2jKibHlrkFokyEtSw24njfxTtAqMLDRgfjrj1enxfcVbZoqvnQKnlVBfvBVKvX67N+QY2MQD1EABGMAh6rRYpcsKhbcLIc290HRFTwdMrvvJT0BDdMsptdfE0H00DlLMIDMbtGzAzJVwOMGvqRtOc7g6chvszLB0Q34ELkvyLbFq3XXitnPmGZMNFagNLurtTLUT8klZxWfuSCYE/GTjg="
  - secure: "JoUuav9FYODC5BpqRy5aCPLCXnf6YUqfgvV4v1WA0+HYJ1cHxDJQy5N8CuAsZuHYlR9p8ky4ziTOv7LVE+/apq4RegTYjNp9HLTsXw6NevurSYZS5B+748i/wZCF6QDgqo/gkr6w3ofho0JI2mn1PO+PPfb9pZ6wvZ5U0nGRnKOGkZ5efH2QpDJx5NxlRNePnVv2G+s/jsfkifi+RQbhoL3AABkv788UiWYkDtYf40UClucTZM1PZC+B3UQXY7HyKaX0RurerkYw8TXRJi29JNXKVXMQZFtq/TIx8FR+C7jNOnb9APzGuvzJ+0/Zv4iLQNeBVe7Jvso6aFEbwJQqnn2dFkEZM3VPejuCgkkvY1viRJd8vz4lhrBgwmZDHfV+ShhF2l94alEsazPx5nNQPvUAtbBuMp3CLRavTaQ6vCAjhWiEtyfI5X7zf2gaO5UnizefjlYOUFI3b2Ymg79LyaqxTaXNBpa1Mje48WHngzCLEEljHWiC7nOsSrA9RWRofTNEXlRWR6SFDBLaPZuvkaCMyeAT7ObdvWJ2+c58IpkMolWjtjt1envNlsEDJnAUzn0cstVuyWLJOPwq+IAFeBsj4DBwMbV3EtGf6MnmhAwmLMrrsL7AzE8/qDHDQrGTiEWRKOXiV3VCRNWzJG2uTfOGdjAbKr6wlQ3Yx+Iyv84="
node_js: 10
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
- wct --configFile=test/src-wct.conf.json --root=. test/src/index.html
- nyc mocha test/src/test.js
- nyc report --reporter=lcov --report-dir=test/coverage
- nyc mocha test/src/testerror2.js
- nyc report --reporter=lcov --report-dir=test/coverage-8-testerror2
- wct --configFile=test/es5-wct.conf.json --root=. --skip-plugin=istanbul --compile=never test/min/index.html
- mocha test/min/test.js
- nvm install 8
- mocha test/min/test.js
- nvm install 6
- mocha test/min/test.js
- if [ "${TRAVIS_BRANCH}" != "" ]; then lcov-result-merger 'test/coverage*/lcov.info' | ./node_modules/coveralls/bin/coveralls.js; fi
