language: node_js
branches:
  except:
  - gh-pages
sudo: false
before_script:
- npm install bower
- npm install -g gulp
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
env:
  global:
  - CXX=g++-4.8
  - secure: "ABOZFV98X1M5YfRql9xXV192NrNlRSrqCZp+gEEUg0Q3EXx1QlBTJFP2ErXLPjCX188+hyF2Vz5OCJkfWe3gBkjlcfRGBkaza0ULNWGcdOXLdhhJ3R+fnxvqnrvCzABaLKEwb4AYYyOnR475Crsb6YQf5+lEgM1XUHjvfJ4+v6uyn0gCeUGMDQ1zU5V4vMY7VsMrXg/xf3/QOb0jTj39CuWGBzoS5Cxl04mIJh0gw6ei6m0btJZQBly40SPYXsCw/6xuqBz137bFBuDUtXBeYc1r7HCaUfkJhSbbI+FvL2rIzUAwdGvYQO4fWxc55Az0GV7EFgbl7f0D2a3GyytZxseQ3wIyuXWPcNKx2CCaPWcA8tj6/Api5gHgXhLW8Qo9q0KvhqvwvRLm/s8aO9K5HwxjcaY5I1pGzdxenxEjzjC+oUrLmjbl0L4H+h3oI0JZjiktA5GkYHMLsk6kH3iWtL2jKibHlrkFokyEtSw24njfxTtAqMLDRgfjrj1enxfcVbZoqvnQKnlVBfvBVKvX67N+QY2MQD1EABGMAh6rRYpcsKhbcLIc290HRFTwdMrvvJT0BDdMsptdfE0H00DlLMIDMbtGzAzJVwOMGvqRtOc7g6chvszLB0Q34ELkvyLbFq3XXitnPmGZMNFagNLurtTLUT8klZxWfuSCYE/GTjg="
  - secure: "JoUuav9FYODC5BpqRy5aCPLCXnf6YUqfgvV4v1WA0+HYJ1cHxDJQy5N8CuAsZuHYlR9p8ky4ziTOv7LVE+/apq4RegTYjNp9HLTsXw6NevurSYZS5B+748i/wZCF6QDgqo/gkr6w3ofho0JI2mn1PO+PPfb9pZ6wvZ5U0nGRnKOGkZ5efH2QpDJx5NxlRNePnVv2G+s/jsfkifi+RQbhoL3AABkv788UiWYkDtYf40UClucTZM1PZC+B3UQXY7HyKaX0RurerkYw8TXRJi29JNXKVXMQZFtq/TIx8FR+C7jNOnb9APzGuvzJ+0/Zv4iLQNeBVe7Jvso6aFEbwJQqnn2dFkEZM3VPejuCgkkvY1viRJd8vz4lhrBgwmZDHfV+ShhF2l94alEsazPx5nNQPvUAtbBuMp3CLRavTaQ6vCAjhWiEtyfI5X7zf2gaO5UnizefjlYOUFI3b2Ymg79LyaqxTaXNBpa1Mje48WHngzCLEEljHWiC7nOsSrA9RWRofTNEXlRWR6SFDBLaPZuvkaCMyeAT7ObdvWJ2+c58IpkMolWjtjt1envNlsEDJnAUzn0cstVuyWLJOPwq+IAFeBsj4DBwMbV3EtGf6MnmhAwmLMrrsL7AzE8/qDHDQrGTiEWRKOXiV3VCRNWzJG2uTfOGdjAbKr6wlQ3Yx+Iyv84="
node_js: 4
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  sauce_connect: true
script:
- wct test/es5/index.html
- cp -vf test/es5-wct.conf.json wct.conf.json
- wct --skip-plugin=istanbul test/es5/index.html
- cp -vf test/es6-wct.conf.json wct.conf.json
- wct test/es6/index.html
- cp -vf test/src-wct.conf.json wct.conf.json
- wct --skip-plugin=istanbul test/src/index.html
- istanbul cover ./node_modules/mocha/bin/_mocha test/es5/test.js --report lcov -- -R spec
- cp -vf test/4-min.istanbul.yml .istanbul.yml
- istanbul cover ./node_modules/mocha/bin/_mocha test/min/test.js --report lcov -- -R spec
- cp -vf test/6.istanbul.yml .istanbul.yml
- nvm install 6
- node --version
- istanbul cover ./node_modules/mocha/bin/_mocha test/es5/test.js --report lcov -- -R spec
- cp -vf test/6-min.istanbul.yml .istanbul.yml
- istanbul cover ./node_modules/mocha/bin/_mocha test/min/test.js --report lcov -- -R spec
- nvm install 7
- node --version
- mocha --harmony_async_await test/src/test.js
- mocha --harmony_async_await test/es6/test.js
- mocha --harmony_async_await test/min/test.js
- if [ "${TRAVIS_BRANCH}" != "" ]; then lcov-result-merger 'test/coverage*/lcov.info' | ./node_modules/coveralls/bin/coveralls.js; fi
