language: node_js
branches:
  except:
  - gh-pages
sudo: false
before_script:
- npm install bower
- npm install -g gulp
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
env:
  global:
  - CXX=g++-4.8
  - secure: "WwU891ODWLYkZ+0XfcBCRer6/SPBlaTEKWoWn1eBqngty4rvXzcEozct/zPYIaesP2kmxzu0TPl3Rdk+AXvanmi14+ZtfgfFIpb73C8DH7kn9qvMQRfC2v2TiqwRqYYWeu8Kmp4JA8RwVn/QhyNgtqlZfp8a81xkbhpDiRF0BIvK+nZb5IRcs2t5lfq+hhJ7h6goFEI6cR9hvgaKQuZEp7GTzj4ilQ5HIP4QyX68duoxS7l5dLlJ2Gh0IaWsdbPpCCwdk9rRTEl/N7pYs8UGdyLAyPKlOvQq8rmj3wfNF/W2sghVL+nX6EQ9A4sktOvuUa0PQg9Yu4RCLW1LO/KVVTM0lMf2B11/KRyos/mxdx43ycEDzi5HauEnt7UwoUarrOfKJPygFpFChHvprhgZ2XdLUCdTwICBH/e94FU2mpypbjkDrFEw3H2lBJ2dsLl6o2LcKXY/ywZXHFWLsqlBAfjWlUzfG8mUjAQ05m5OLtpf4PKwyWJrn3UnJVp9eWPw98tsqpH/o+jVymOxJr6A3xdhP8MqZiSpAjuuqheMEFI3BFICDPFBizM4VGdXGSc0+bne6PXuetjfg+omxe0s19cMipPKgFPl6q4sF6fSgxIACNkYF75kcDjl37W1gXghDtBh/rX43/hrCxfqrRbi24ZgWtiNpsXRLYcyphm08wc="
  - secure: "JoUuav9FYODC5BpqRy5aCPLCXnf6YUqfgvV4v1WA0+HYJ1cHxDJQy5N8CuAsZuHYlR9p8ky4ziTOv7LVE+/apq4RegTYjNp9HLTsXw6NevurSYZS5B+748i/wZCF6QDgqo/gkr6w3ofho0JI2mn1PO+PPfb9pZ6wvZ5U0nGRnKOGkZ5efH2QpDJx5NxlRNePnVv2G+s/jsfkifi+RQbhoL3AABkv788UiWYkDtYf40UClucTZM1PZC+B3UQXY7HyKaX0RurerkYw8TXRJi29JNXKVXMQZFtq/TIx8FR+C7jNOnb9APzGuvzJ+0/Zv4iLQNeBVe7Jvso6aFEbwJQqnn2dFkEZM3VPejuCgkkvY1viRJd8vz4lhrBgwmZDHfV+ShhF2l94alEsazPx5nNQPvUAtbBuMp3CLRavTaQ6vCAjhWiEtyfI5X7zf2gaO5UnizefjlYOUFI3b2Ymg79LyaqxTaXNBpa1Mje48WHngzCLEEljHWiC7nOsSrA9RWRofTNEXlRWR6SFDBLaPZuvkaCMyeAT7ObdvWJ2+c58IpkMolWjtjt1envNlsEDJnAUzn0cstVuyWLJOPwq+IAFeBsj4DBwMbV3EtGf6MnmhAwmLMrrsL7AzE8/qDHDQrGTiEWRKOXiV3VCRNWzJG2uTfOGdjAbKr6wlQ3Yx+Iyv84="
node_js: 4
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  sauce_connect: true
script:
- wct test/es5/index.html
- istanbul cover ./node_modules/mocha/bin/_mocha test/es5/test.js --report lcov -- -R spec
- if [ "${TRAVIS_BRANCH}" != "" ]; then lcov-result-merger 'test/coverage*/lcov.info' | ./node_modules/coveralls/bin/coveralls.js; fi
